### ISSUE TITLE
搜索思域或者杨颖还是出现的热搜

### ISSUE THREAD

**Issue by roverk8y** [yaowenxu/Hot-Search-Killer#1]
搜索"思域"或者"杨颖"还是出现的热搜框，然后我看了下代码，在搜索思域的时候，div的class由FYB_RD变成的FYB_BD,我想应该在代码中加入对BD的隐藏就应该可以解决

**Comment by yaowenxu** [comment]
是的，应该是这么个方法。这个仓库，好久之前写的了，你fork一下，修改一下就好。
