### ISSUE TITLE
How clear the "hot search" in homepage?

### ISSUE THREAD

**Issue by Baileyus** [yaowenxu/Hot-Search-Killer#2]
The function of clearing hot search is realized on the search page, but I want to realize it on the home page.
Is it possible?
:)

**Comment by yaowenxu** [comment]
咦，我的Baidu主页好像没有显示热搜，你看看是不是可以通过设置把热搜推荐关掉；如果想清除主页的元素的话，看一下网页源码，把热搜那块对应的div设置为隐藏就好，很简单，在油猴脚本[对应位置](https://github.com/yaowenxu/Hot-Search-Killer/blob/f8808fb96e4bc559e12f1aed00c4c9293af36b10/Tamper%20Monkey%20Script/%E7%99%BE%E5%BA%A6%E6%90%9C%E7%B4%A2%E7%83%AD%E7%82%B9%E8%BF%87%E6%BB%A4%E5%99%A8.user.js#L51)修改代码即可：
```js
// 主模块，执行DOM 过滤操作
function removeAD(){
    var dom = $(".FYB_RD"); // 这里
    console.log(dom);
    dom.hide();
}
```
